//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2016.Data_Tier
{
    using System;
    using System.Collections.Generic;
    
    public partial class played
    {
        public int artist_id { get; set; }
        public int album_id { get; set; }
        public int track_id { get; set; }
        public System.DateTimeOffset played1 { get; set; }
        public int user_id { get; set; }
    
        public virtual album album { get; set; }
        public virtual artist artist { get; set; }
        public virtual track track { get; set; }
        public virtual user user { get; set; }
    }
}
